### ISSUE TITLE
Clang 14 CI builds are failing (Ubuntu 22.04 runners)

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/questions-and-answers#101]
GitHub-hosted Ubuntu 22.04 runners currently use Clang 13.0.1, 14.0.0 and 15.0.7 ([ref](https://github.com/actions/runner-images/blob/8986c1bb8f2af04d01e7f3a595b0a20f475eafb6/images/ubuntu/Ubuntu2204-Readme.md#L15)), where Clang 14 is the default (same as the [apt default](https://packages.ubuntu.com/jammy/clang)). Since YARP 3.11, our CI builds are failing due to its dependency on C++20, see https://github.com/robotology/yarp/pull/3167#issuecomment-2621652712 (BTW downstream projects still consume C++17, that follow-up change to `target_compile_features()` was later reverted in [3.11.1](https://github.com/robotology/yarp/releases/tag/v3.11.1), see https://github.com/robotology/yarp/pull/3182).

It turns out that Clang 15, which is already installed on the runner images, seems to solve this issue (https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/451fcd773070e8642dfb5cc84ef0740307f955c7, [logs](https://github.com/user-attachments/files/19821182/logs_37345177546.zip)). However, integrating that in the workflow YAML will make things look a bit clumsy due to the inclusion/exclusion policy of [`jobs.<job_id>.strategy`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategy) ([manual](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow)). Since it is not possible to override matrix entries, this should be done by coordinating `matrix.include` and `matrix.exclude` like [this](https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/5010df11fabd355815adda590d275c7d54db237b) (spoiler: it didn't work due to some obscure syntax error). At roboticslab-uc3m, we call this "ñapa" and I think it's only beautiful on the linguistic plane; I'd rather refrain from maintaining such code in the long run.

To sum up, I see two solutions:
- skip Clang builds on Ubuntu 22.04 runners altogether, perhaps until GH maintainers decide to make Clang 15 the new default
- explicitly state the compiler version (either GCC or Clang) associated to each Ubuntu release, making it match the apt default except for Ubuntu 22.04 and Clang

The second option should be preferred regarding CI coverage, I just have to check the complexity of the resulting YAML code. Besides, our users would need to upgrade their Clang anyway if working on Ubuntu 22.04, so these CI jobs will be actually useful.

Current shape (for the record):

```yaml
strategy:
  fail-fast: false
  matrix:
    os: [ubuntu-22.04, ubuntu-24.04]
    robotology:
    - { yarp: yarp-3.10, cmake: 3.19.x }
    - { yarp: yarp-3.11, cmake: 3.19.x }
    - { yarp: master, cmake: 3.19.x }
    compiler:
    - { cc: gcc, cxx: g++ }
    - { cc: clang, cxx: clang++ }
    experimental:
    - ${{github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'}}
    exclude:
    - { experimental: false, robotology: { yarp: master } }
```

**Comment by PeterBowman** [comment]
I've come up with this:

```yaml
strategy:
  fail-fast: false
  matrix:
    system:
    - { os: ubuntu-22.04, compiler: { cc: gcc-11, cxx: g++-11 } }
    # https://github.com/roboticslab-uc3m/questions-and-answers/issues/101
    - { os: ubuntu-22.04, compiler: { cc: clang-15, cxx: clang++-15 } }
    - { os: ubuntu-24.04, compiler: { cc: gcc-13, cxx: g++-13 } }
    - { os: ubuntu-24.04, compiler: { cc: clang-18, cxx: clang++-18 } }
    robotology:
    - { yarp: yarp-3.10, cmake: 3.19.x }
    - { yarp: yarp-3.11, cmake: 3.19.x }
    - { yarp: master,    cmake: 3.19.x }
    experimental:
    - ${{github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'}}
    exclude:
    - { experimental: false, robotology: { yarp: master } }
```

Other solutions involving the `include` property failed due to overwriting previous entries.

See also (didn't help me here, but rendered interesting anyway):

- https://github.com/orgs/community/discussions/24981
- https://stackoverflow.com/questions/66025220/paired-values-in-github-actions-matrix
