### ISSUE TITLE
Simplify code coverage in CI builds

### ISSUE THREAD

**Issue by PeterBowman** [roboticslab-uc3m/questions-and-answers#50]
Our Travis lines for code coverage (via Coveralls) look like this ([source](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/3169aa927eae1ea75dbd6058d5619ebc837ee13e/.travis.yml)):

```yaml
install:
  # see http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/
  - if [ "$CXX" = "g++" ]; then wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz; fi
  - if [ "$CXX" = "g++" ]; then tar xf lcov_1.11.orig.tar.gz; fi
  - if [ "$CXX" = "g++" ]; then sudo make -C lcov-1.11/ install; fi
  - if [ "$CXX" = "g++" ]; then gem install coveralls-lcov; fi

after_success:
  # capture coverage info
  - if [ "$CXX" = "g++" ]; then lcov --directory . --capture --output-file coverage.info; fi
  # filter out system and test code
  - if [ "$CXX" = "g++" ]; then lcov --remove coverage.info  '/usr/*' 'tests/*' --output-file coverage.info; fi
  # debug before upload
  - if [ "$CXX" = "g++" ]; then lcov --list coverage.info; fi
  # uploads to coveralls
  - if [ "$CXX" = "g++" ]; then coveralls-lcov --source-encoding=ISO-8859-1 coverage.info; fi
```

Perhaps a bit too convoluted if we take a look at official docs:

* https://docs.travis-ci.com/user/coveralls/
* https://github.com/eddyxu/cpp-coveralls#linux (Travis example)

Copy-paste from the latter:

```yaml
language: cpp
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - ./configure --enable-gcov && make && make check
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
```

More links (compiler flags et al.):

* https://stackoverflow.com/questions/16682606/how-to-resovle-gcov-init-undefined-reference-issue-when-link
* https://stackoverflow.com/questions/11783932/how-to-add-linker-or-compile-flag-in-cmake-file
* https://codeflu.blog/2014/12/26/using-gcov-and-lcov-to-generate-beautiful-c-code-coverage-statistics/
* https://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/
* https://github.com/ainfosec/ci_helloworld/blob/7e026ca/.travis.yml#L224-L249
